sequenceDiagram
    actor Developer
    Developer->>+GitHub: git push
    GitHub->>+Jenkins: Webhook
    Jenkins->>GitLab: Build image
    Jenkins->>-Kubernetes: Update
    activate Kubernetes
    Kubernetes->>GitLab: Get image
    GitLab-->>Kubernetes: 
    Kubernetes->>Vault: Decrypt config file
    Vault-->>Kubernetes: 
    deactivate Kubernetes
